### ISSUE TITLE
Optional shared objects

### ISSUE THREAD

**Issue by sebastian-peter** [carueda/tscfg#124]
**Describe the bug**
Shared objects that are marked as optional in a comment, are not wrapped in `scala.Option`. 
In Java with `--java:optionals` enabled, `java.util.Optional` is not used either.

**To Reproduce**
```
#@define
Shared {
  c: string
  d: int
}

example {
  # @optional
  a: Shared
}
```

results in:
```scala
final case class Example(
  a : ExperimentsConfig.Shared
)
```

**Expected behavior**
```scala
final case class Example(
  a : scala.Option[ExperimentsConfig.Shared]
)
```

**Target language(s):**
 - Scala
 - Java

**Additional context**
In `ScalaGen.scala:95`, the type is wrapped in `scala.Option`. This type is not used in `ScalaGen.scala:109`, where the type name for ObjectRefTypes is generated.
Analogously in `JavaGen.scala:98` for Java generation.
(at least, this is my interpretation of what is happening)

**Comment by carueda** [comment]
Thanks for entering this issue, which has actually been known for a while as noted in the readme:

> Note: current support is in terms of the referenced object always being required. In other words, a: "Struct?", as an example, is not supported. Also, the @define annotation is only supported for objects and enumerations (see below), not for a basic types or lists.

But good to have an explicit entry in the tracker for when the time comes to address it. Thanks again.

**Comment by sebastian-peter** [comment]
I missed that note, my bad. This issue could then be considered a feature request rather than a bug.
Anyhow, since our project would benefit from this, I'll gladly look into this if I can find some time this week.

**Comment by carueda** [comment]
Thanks for the offer!  And, let's keep it as a bug because full support (as with any other type) is certainly what makes more sense. The current limitations have been due to time constraints.
