### ISSUE TITLE
Getter is created for shared object definition in Java

### ISSUE THREAD

**Issue by sebastian-peter** [carueda/tscfg#125]
**Describe the bug**
Found another bug during fixing #124. Getters for shared object definitions are created, which does not make sense and results in compile errors.

**To Reproduce**
Generate java config class with `--java:getters` for:
```
#@define
Shared {
  c: string
  d: int
}

example {
  a: Shared
}
```

results in generated config with line 5:

```java
public final Config.Shared getShared() { return Shared; }
```

**Expected behavior**
This line should not be generated.

**Target language(s):**
 - Java

**Additional context**
//

**Comment by carueda** [comment]
I just entered #127 , a related pending fix which should probably be addressed first (or along with this one).
