### ISSUE TITLE
Wrapped Data Types

### ISSUE THREAD

**Issue by t-ober** [carueda/tscfg#180]
First of all thanks for your work regarding this useful project 🙂 

I'm wondering if there is a way to define a data type that uses a different data type as one if its parameters. 

e.g.:

```
#@define
TypeA {
    fizz: String
    buzz: String
}

#@define
TypeB = {
    foo: TypeA
    bar: TypeA
}

cfg {
    typeB = TypeB
    additionalParam = String
}
```

Currently `TypeB` gets interpreted as : 

```
  final case class TypeB(
    bar : java.lang.String,
    foo : java.lang.String
  )
```

This would be super helpful to avoid code duplication and make configuration data handling much easier.

**Comment by carueda** [comment]
@t-ober - thanks for the note!

This should work, I'll take a closer look, but #71 seems related.

**Comment by t-ober** [comment]
That was quick. Thanks for taking care of this! 🙂
