### ISSUE TITLE
Option to generate getters

### ISSUE THREAD

**Issue by bhchandra** [carueda/tscfg#31]
I am unable to mock generated Conf class for testing with Mockito even after enabling mocking final classes/methods in Mockito.

This is failing with Mockito.when(...).thenReturn(...);
I am guessing this is because Mockito can mock only method calls.

**Comment by carueda** [comment]
Could you elaborate a bit?  I'm not referring to the Mockito part per se, but the need for mocking the configuration in the first place. Is it perhaps that there's not direct way to instantiate the config classes (other than via a Typesafe Config object)?

**Comment by bhchandra** [comment]
Sorry for the late reply.

>  Is it perhaps that there's not direct way to instantiate the config classes (other than via a Typesafe Config object)?

I am not exactly sure what you mean.
 


The problem is that the class under test is tightly coupled with the Conf object, but requires only single configuration parameter (bad desgin). So the simple thing required for testing is Mockito.when(conf.getA()).thenReturn(x), which is not possible.
To test the class, I now need to create Typesafe Config object with all the required configuration parameters. This is good if I am doing an integration test but seems like extra work for unit testing.


_Thank you for bringing type safety and auto completion to configuration._

**Comment by carueda** [comment]
@bhchandra I've just implemented your suggestion, the new option is `--java:getters`.  Hope it covers what you need.  Thanks for using tscfg.

**Comment by carueda** [comment]
@bhchandra I've just implemented your suggestion, the new option is `--java:getters`.  Hope it covers what you need.  Thanks for using tscfg.
