### ISSUE TITLE
Please publish 0.9.3 to maven central.

### ISSUE THREAD

**Issue by bhchandra** [carueda/tscfg#32]

**Comment by carueda** [comment]
Sorry, it seems it didn't get published back then ... will retry now...

**Comment by carueda** [comment]
Seems like it's now published:
   https://oss.sonatype.org/content/repositories/releases/com/github/carueda/tscfg_2.12/0.9.3/

(although not yet showing up in http://search.maven.org/).

**Comment by bhchandra** [comment]
Thank you.

**Comment by carueda** [comment]
Just checked, it is now on http://search.maven.org/#search%7Cga%7C1%7Ccarueda
