### ISSUE TITLE
Create a default annotation for objects

### ISSUE THREAD

**Issue by JustinPihony** [carueda/tscfg#33]
Right now you can enter a default config such as this:

```
endpoint {
  url: "String | http://example.net"
}
```

However, if `endpoint` is not entered into the final config then you end up with a missing config exception. And optional does not work because it results in a None, which cannot reference the url property. 

So, my proposed solution is to add a top level annotation to denote that objects themselves should use defaults if they exist. 

Instead of `config.endpoint.url` throwing an exception because endpoint doesn't exist it will instead create the `endpoint` object and let the final property referenced determine if an exception or default should be used.

**Comment by JustinPihony** [comment]
If you are open to accepting this idea then I can implement it. I want to check if you are amenable to it first, though.

**Comment by carueda** [comment]
This has been a weak point of the tool so thanks much for your offer to address it!

Your proposed solution sounds good in general, but here's a couple of comments: 

a)

> However, if `endpoint` is not entered into the final config then you end up with a missing config exception

Your are right, and I would in principle consider this a bug by itself, that is, independent of any additional annotations.

b)

Perhaps allow the optional nature of an object to be _implicit_ under the following definition:

_Implicit optional object_: An object will automatically be considered optional if and only if all its attributes are optional (either explicitly or -recursively- implicitly) or with default values. Your example above would be an example. One other example:

```
endpoint {
  url: "String | http://example.net"
  foo: "int?"
  baz {
    key: "bar"
  }
}
```

c)

> So, my proposed solution is to add a top level annotation to denote that objects themselves should use defaults if they exist.

In principle, I like the idea of making things explicit, at least for the sake of documentation at the config spec level. But, considering the previous points, do we actually need a new annotation?

Thanks again!

**Comment by JustinPihony** [comment]
@carueda Given your response I went ahead and treated it as a bug, and created #34 

Note that the only downside I can see is that the error will say that the value does not exist in the case of no default value - when in reality it is the entire path to the value. But this seems as though it shouldn't be that big of a deal. If this point is ignorable, then this ends up being a relatively simple fix.

**Comment by carueda** [comment]
The merged PR https://github.com/carueda/tscfg/pull/34 referred to issue #33 but should have been to issue #34 (so, reopening this one)

**Comment by carueda** [comment]
@JustinPihony I just renamed this to better align with the corresponding PR.

I don't quite follow your "downside" comment above (maybe too much multitasking in my brain right now).. could you elaborate?  Do you want to continue the "additional annotation" discussion in another issue, or can we consider this basically in good share already with your fix?

**Comment by JustinPihony** [comment]
The downside is minimal and probably not worth any further thought. It's just that the error will now be different. Given the simple spec with a required url:

```
endpoint{
  url: "String"
}
```

The old logic of an absent endpoint and trying to reference `endpoint.url` would yield an exception akin to "endpoint does not exist". This would point to the first point of absent configuration. Whereas now the error will be akin to "url does not exist", which will require going backwards from url to find the totality of the missing config. Again, it's a minor change and probably not that big of a deal, but I wanted to at least point it out.

As to the additional annotation, if you're good with this fix and nobody has any problems then I'm fine leaving it as is.

**Comment by carueda** [comment]
Gotcha, thanks  (and I just entered #36 --comments welcome).

Yes, I'm good with this fix.

**Comment by JustinPihony** [comment]
Thanks for the update, but I just checked and 0.9.4 does indeed contain this fix. I just tested by downgrading to 0.9.3 and saw the same code (different generated config) fail for this issue. I'm not sure what gave you the impression that it wasn't included.

**Comment by carueda** [comment]
Hmm, now I'm not so sure... (some incorrect command, or something else) ; )  Anyway, no issues now, thanks for the reply!
