### ISSUE TITLE
Generating java.time.Duration instead of long.

### ISSUE THREAD

**Issue by qux42** [carueda/tscfg#37]
Mit config.getDuration("path") bekommt man eine java.time.Duration.
Es wäre schön, wenn tscfg darauf erweitert werden könnte und anstatt eines Longs eben die Duration (java8 oder neuer) zurückliefert.

**Comment by carueda** [comment]
With google translate's help:

>With config.getDuration ("path") you get a java.time.Duration.
It would be nice if tscfg could be extended to that and instead of a long just the duration (java8 or newer) returns.

Thanks for the suggestion!

**Comment by qux42** [comment]
#45

**Comment by carueda** [comment]
(Ah just noted there was not `resolve #37` (or similar) in the commit to auto-close this issue. )

This feature was added in https://github.com/carueda/tscfg/releases/tag/v0.9.9
