### ISSUE TITLE
String-to-bytes conversion results in compilation error

### ISSUE THREAD

**Issue by opensorceror** [carueda/tscfg#40]
First of all, I'd like to thank you for this library. This makes mapping Typesafe config files to objects a breeze!

I'm noticing an issue with the string-to-bytes conversion. If I specify a large number, such as:

    memory: 50G

The resulting code is generated as:

    memory = if(c.hasPathOrNull("memory")) c.getBytes("memory") else 53687091200

The compiler then throws an error saying 53687091200 is outside the range of `Int`. If I convert this to a long (53687091200L), it works. But this adds a manual element to the code generation; I must now manually fix this every time I use tscfg regenerate the code.

Moreover, if I change the specification to:

    memory: "string | 50G"

the generated code is:

    memory = if(c.hasPathOrNull("memory")) c.getString("memory") else "50G"

However, if I load the config using Typesafe's `ConfigFactory.load()` method, and if I then initialize the generated class, I see this in the initialized object:

    memory = "string | 50G"

So it looks like despite generating the code correctly, initializing the generated class using a Typesafe `Config` object does not parse everything correctly.

I highly recommend that if a key has a string value in the Typesafe config file, the code generator should not implicitly convert it to bytes. Of course, if it is not a string (as determined by the absence of quotes), it should convert it to bytes as is done currently.

**Comment by carueda** [comment]
Hey @opensorceror Thanks for the bug report about the wrong literal for what should be a `long`.  I'll fix this in due course.

Sorry, I'm less sure about the second part of your report (starting with "Moreover,...").  Would you mind entering a new ticket for that? Thx!
