### ISSUE TITLE
Size-in-bytes should be explicitly indicated in config spec

### ISSUE THREAD

**Issue by opensorceror** [carueda/tscfg#42]
Size-in-bytes conversion should be explicitly (not optionally) specified by user using `size | <size>`. Unless this is explicitly specified, tscfg should assume it is a string by default; no implicit conversion should be done. (This is also the default behaviour of Typesafe Config.)

**Example:**

In each of the following cases, tscfg currently generates a variable `memory` of type **`Long`**, with value `53687091200`. 

    memory: 50G
    memory: "50G"

To be consistent with the default behavior of Typesafe Config, which doesn't make assumptions about types unless explicitly requested (e.g., using methods such as `getBytes`, `getInt`, etc), tscfg should instead generate a variable `memory` of type **`String`**, with value "50G". This should be the default behavior, unless the user explicitly requests a size-in-bytes comparison as follows:

    memory: "size | 50G"

(This has been discussed at length in #41).

**Comment by crixal** [comment]
`optional` annotation is used because default value for list type is not available. I create issue with this problem.

**Comment by carueda** [comment]
Hi @opensorceror ... sorry it took a while but this has been implemented and will be available in 0.9.984.
