### ISSUE TITLE
"[string]" type results in regular string instead of List

### ISSUE THREAD

**Issue by timvlaer** [carueda/tscfg#46]
When I define the following in my config spec:
```
userIds: [string] // ok
userIds: "[string]" // quotes -> result in regular String type instread of List<String>
```
I wonder if this is expected behaviour?

**Comment by timvlaer** [comment]
I came to this because I'd like to create an optional list, but a question mark is not allowed outside quotes. 
```
userIds: "[string]?"
```

**Comment by carueda** [comment]
> I wonder if this is expected behaviour?

well, yes.  The simple reason is that the parsing used by the tool is via the Typesafe Config itself.

> I came to this because I'd like to create an optional list

No problem; just use the [`#@optional`](https://github.com/carueda/tscfg#optional-object-or-list) annotation:

```
#@optional
userIds: [string]
```

Please reopen this if that's not working for some reason. Thanks!

**Comment by timvlaer** [comment]
Cool, thanks for the feedback. That should be sufficient for my use case,
I'll give it a try.
