### ISSUE TITLE
Option to generate singleton constructor or static instance

### ISSUE THREAD

**Issue by abonander** [carueda/tscfg#48]
There's a couple different patterns here I'd like to discuss; we've been switching between them at work in our handwritten boilerplate for Config and I was hoping this code generator could be extended to add one or the other or both.

Our apps just load their config once on startup, so it made sense to have the code executed in a `static` so it can be available everywhere; this does cause quite a bit of coupling which we will have to deal with later but it's great for rapid prototyping, especially if you don't expect the config to change.

### Singleton Pattern
Our first attempt just used a singleton pattern, so with the codegen example from README it just looks like this:

```java
public class Cfg {
  public final Service service;
  public static class Service {
    public final boolean debug;
    public final double factor;
    public final int poolSize;
    public final String url;
  }

  private static Cfg INSTANCE;
  public static final getInstance() {
    if (INSTANCE == null) INSTANCE = new Cfg(ConfigFactory.load());
    return INSTANCE;  
  }
}
```

Since we can't modify generated code because it can be overwritten at any point, it would be nice if the generator added something like this for us so we don't have to stick it in another class.

### Statics Pattern
An alternative pattern we came up with that I've personally become more attached to is to just have a hierarchy of classes with `static final` fields, e.g. with the same example:

```java
public class Cfg {
  private Cfg() {}

  private static final Config config = ConfigFactory.load();

  public static class Service {
    private Service() {}

    public static final boolean debug = config.getBoolean("service.debug");
    public static final double factor = config.getDouble("service.factor");
    public static final int poolSize = config.getInt("service.poolSize");
    public static final String url = Config.getString("service.url");
  }
}
```
It's kind of bad style but it looks really nice in usage:

```java
Service.bind(Cfg.Service.url);
```

This avoids calling `getInstance()` everywhere which is really just line noise.

**Comment by carueda** [comment]
I'm not sure this justifies any changes in the generation.

>  Since we can't modify generated code because it can be overwritten at any point, it would be nice if the generator added something like this for us so we don't have to stick it in another class.

Actually "sticking another class" is a pattern I've seen used out there (and I use it myself). In fact, it facilitates adding logic/validation at construction time (for example, to check that filenames or regexes are valid, etc.)

> .. This avoids calling getInstance() everywhere ...

For immediate static initialization and ability to directly refer to configuration entries from client code, why not something like the following:

```java
package somepkg;

public class AppSettings {
  public static final Cfg cfg = new Cfg(ConfigFactory.load());
}
```

Then, in client code:
```java
import static somepkg.AppSettings.cfg
[...]
Service.bind(cfg.service.url);
```

**Comment by carueda** [comment]
@abonander just wondering if you have any further thoughts..
