### ISSUE TITLE
Regex not properly captured

### ISSUE THREAD

**Issue by Ankoul** [carueda/tscfg#55]
Hello, 
I am having some problem with regex inside string, so I would like to know if is there any way to exclude some keys from building?

My config file has this key:
`regex = ">(RUS00),(\\d{12})(.\\d{7})(.\\d{8})(\\d{3})(\\d{3}),(\\d{1,10})((\\.)(\\d{3}))?"`

It works fine in my project, but i got this error on tscfg:
_String: 1: Expecting a value but got wrong token: 'd' (backslash followed by 'd', this is not a valid escape sequence (quoted strings use JSON escaping, so use double-backslash \\ for literal backslash)) (if you intended 'd' (backslash followed by 'd', this is not a valid escape sequence (quoted strings use JSON escaping, so use double-backslash \\ for literal backslash)) to be part of a key or string value, try enclosing the key or value in double quotes, or you may be able to rename the file .properties rather than .conf)_ 

It works only if my regex is commented, so actually I am commenting my regex line every time I use tscfg.

**Comment by carueda** [comment]
@Ankoul , this looks like a regression, this well-formed regex should be accepted; thanks for the report!

**Comment by carueda** [comment]
@Ankoul thanks again for reporting this issue, which should now be fixed in v0.9.93. Please give it a try. I also have apps with regexes in their config, so this regression was just lurking there waiting to get exposed for me as well.

**Comment by Ankoul** [comment]
I am glad to be helpful. I didn't think you would fix it so fast, so this is why I asked about an exclusion option. Thank you so much.

**Comment by carueda** [comment]
great, thanks for the testing too!  (btw, if not already, please consider a star `;)`)
