### ISSUE TITLE
generate conf template

### ISSUE THREAD

**Issue by carueda** [carueda/tscfg#6]
Configuration templates are often a means to provide end users with a description of the properties that should be set for the proper operation of an application or library. Based on the template, end users will then enter the concrete settings that are appropriate.

On the other hand, configuration "specs," as used for tscfg generation, are mainly intended to be used by the developer of such application or library.

The proposal here is about adding an option to also generate a template configuration file from the given spec so the developer does not have to manually create/edit such templates.

For example, from the spec

``` properties
# Some description of the endpoint section 
endpoint {
  # The path associated with the endpoint
  path = "string"

  # Port where the endpoint service is running
  port = "int | 8080"

  # Email to send notifications to. If missing, no emails are sent.
  email = "string?"
}
```

the generated template could look something like

``` properties
# Some description of the endpoint section 
endpoint {
  # 'path': Required string.
  # The path associated with the endpoint
  path =   

  # 'port': Optional integer. Default value: 8080
  # Port where the endpoint service is running
  #port =

  # 'email': Optional string.
  # Email to send notifications to. If missing, no emails are sent.
  #email = 
}
```

**Comment by carueda** [comment]
Implemented in 0.3.0

**Comment by carueda** [comment]
Removed in 0.5.0.

**Comment by ketan** [comment]
Was there a particular reason for removing this? It's an excellent way to generate good documentation about the config file, very much like how apache's configuration file.

**Comment by carueda** [comment]
It was removed as part of a complete reimplementation of the tool, and given that this particular feature was not very high in the priority list. Will look into re-incorporating it, at least to some basic level. Thanks for your interest.

**Comment by carueda** [comment]
See https://github.com/carueda/tscfg/wiki/template-generation

**Comment by ketan** [comment]
Thanks a lot for this quick fix. When can we expect to see a release
published to maven central?

**Comment by carueda** [comment]
Yes, "published" already, but you know, it takes a little bit to get to maven central from sonatype...

> Feel free to "star" this project if you are so inclined `; )`
