### ISSUE TITLE
Consider inheritance tree in traversing members

### ISSUE THREAD

**Issue by ckittl** [carueda/tscfg#67]
I noticed some difficulties in traversing member structs when using the new inheritance feature (many thanks for that!). Think of my following example config:

```
#@define abstract
AbstractA {
  a: string
}

#@define extends AbstractA
ImplA {
  b: string
}
```

Parsing this config to Scala config class aborts with `IllegalArgumentException` thrown in `ModelBuilder:210`, as the parent of `ImplA` cannot be found.

Here is, what is happening: In `ModelBuilder:85` it is ensured, that at first the shared objects are processed and added to the name space, without any further distinction among the shared objects. In my case by incident at first `ImplA` definition and then `AbstractA` definition should be traversed. Therefore `AbstractA` is not known to the name space on attempt to add `ImplA` leading to the described exception.

I would propose to extend the ordering logic in `ModelBuilder:85` to utilize an inheritance tree of shared objects. This would also allow inheritance of abstract shared objects then, e.g.

```
AbstractA
-- AbstractAA
---- ImplAA
-- AbstractAB
---- ImplAB
...
```

and the logic wouldn't rely on the order in which the user provides the shared object definitions.

Additionally, this might come in handy for #66 of @johanneshiry as then case class members (leaf nodes) can easily be identified.

If I can provide you anything further for a better understanding of my issue, please just let me know. If you two wish for some support on this, please also just give me a little hint. 😉

**Comment by johanneshiry** [comment]
You're right on this. I didn't touch the ordering of `#@define` as I couldn't manage to produce a case as yours but maybe I should have checked more carefully. I just saw, that @carueda did some changes on the ordering and started implementing enum support (unreleased on current master branch). Maybe he already noticed and addressed your issue?

**Comment by carueda** [comment]
Thanks @ckittl for the report and willingness to contribute!  Yes, this new capability requires a resolution mechanism like that (unneeded before because there was no `@define` interdependency ).  Let me take a closer look and throw some ideas.

**Comment by carueda** [comment]
@ckittl Please take a look at that commit, which should facilitate implementing a fix for this issue. In concrete, it would be a matter of using any `@define` interdependency [here](https://github.com/carueda/tscfg/blob/eccee9a16e7f48001dc228c45b2ad5dac215c6a5/src/main/scala/tscfg/ModelBuilder.scala#L94) to do an appropriate ordering.  I also added `issue67.spec.conf` (for now skipped via `--skip-gen4tests` in the source(*)) as preparation for corresponding java and scala tests.  Hope that helps if you want to go ahead with a PR!  Let me know. Thanks again.

(*) which as you know can still be manually generated, eg:

    > runMain tscfg.Main --spec src/main/tscfg/example/issue67.spec.conf --scala --cn ScalaIssue67Cfg --dd src/test/scala/tscfg/example

**Comment by ckittl** [comment]
Looks good to me! The changes are pretty much what I also thought about.

I'm a bit short on time the upcoming week, but if you wish so, I will try to find some time for a proposal via PR.

**Comment by carueda** [comment]
No rush, I would also have to find some time. Just let me know if you would like to complete this at some point and I'll let you go ahead with a PR at your convenience.  Otherwise, no problem, I'd put this in my todo for a next session on tscfg (or maybe @johanneshiry would be interested ; )

btw,  just some quick additional comments now, at least to make it easier to resume work on this when the time comes (and not that all of these should be addressed necessarily):

- consideration for namespace in the order of @defines
- should we consider something similar to linearization order à la Scala for the appropriate order?
- check for @define interdependency cycles, throwing an error if there's any

**Comment by ckittl** [comment]
I handed in a draft PR, so you can keep track of the changes (see above).

Additionally, I added some tasks, so that it is clear, what is in the scope of the PR and what not.

Would you be able to explain "consideration for namespace in the order of `@defines`" a little more detailed? I'm afraid I cannot get your exact point just with that statement.

**Comment by carueda** [comment]
@ckittl just to note I'm hoping to review your PR soon, thanks again for your patience.
