### ISSUE TITLE
Hardcoded example code in ScalaGen.scala

### ISSUE THREAD

**Issue by sebastian-peter** [carueda/tscfg#74]
At ScalaGen.scala:529, the path is hardcoded to `parentPath + "fruit"`, while it should be `parentPath + "$path"` (as far as I can tell). 

The corresponding tests at ScalaMainSpec.scala:748ff do not fail because they are all fruit-related 🍌🍎🍍.

**Comment by carueda** [comment]
Thanks for the catch!   😂

(I added an associated test)

**Comment by sebastian-peter** [comment]
Thank you very much!
